### ISSUE TITLE
'You cannot serialize or unserialize PDO instances' 

### ISSUE THREAD

**Issue by skiracerdude** [skiracerdude/eCommerceCaseStudy#12]
Fatal error: Uncaught exception 'PDOException' with message 'You cannot serialize or unserialize PDO instances' in [no active file]:0 Stack trace: #0 [internal function]: PDO->__sleep() #1 {main} thrown in [no active file] on line 0

**Comment by crimsonFuckr** [comment]
And what can I do about that. I told you.
workaround = set uid to session and create user object everytime we need it (ie change profile info)
