### ISSUE TITLE
Delete button on a post doesn't delete

### ISSUE THREAD

**Issue by skiracerdude** [skiracerdude/eCommerceCaseStudy#32]
The X in the top corner doesnt delete anything. 

Also a modal dialogue to confirm post deletion would be a good idea.

**Comment by skiracerdude** [comment]
Update: Delete works on wall, just not on timeline

**Comment by crimsonFuckr** [comment]
We didn't write it for timeline.. It doesn't even show the button I think?

**Comment by skiracerdude** [comment]
There is an x on posts on the timeline


Alex Stojda

Sent by Outlook for Android






On Sat, Nov 28, 2015 at 11:46 AM -0800, "crimsonFuckr" <notifications@github.com> wrote:





We didn't write it for timeline.. It doesn't even show the button I think?

---
