### ISSUE TITLE
Notice: Undefined index: post_id in [...]/includes/models/Post.php on line 50

### ISSUE THREAD

**Issue by skiracerdude** [skiracerdude/eCommerceCaseStudy#33]
This error is produced on the page: http://www.devbana.tk/groups/group?g=1

http://i.icap.me/2131448721782b7eb.png

**Comment by crimsonFuckr** [comment]
Probably forgot some safety check. isset ftw. I'll check it out.

**Comment by Evi1NoOb** [comment]
andrew fixed this on mine. idl if he commited it. it will be in one of mine. please close this when you can confirm @skiracerdude

**Comment by crimsonFuckr** [comment]
Should be gone. reopen if problems. @skiracerdude
